apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: submit-api
  namespace: cjob-system
spec:
  selector:
    matchLabels:
      app: submit-api
  endpoints:
    - port: http
      path: /metrics
