apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-cjob-config.yaml
  - configmap-postgres-schema.yaml
  - pvc-cli-binary.yaml
  - rbac-submit-api.yaml
  - rbac-dispatcher.yaml
  - networkpolicy-allow-submit-api.yaml
  - networkpolicy-allow-metrics-scrape.yaml
  - postgres/statefulset.yaml
  - submit-api/deployment.yaml
  - submit-api/servicemonitor.yaml
  - dispatcher/deployment.yaml
  - watcher/deployment.yaml
  - watcher/podmonitor.yaml
