apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-cjob-config.yaml
  - configmap-postgres-schema.yaml
  - pvc-cli-binary.yaml
  - rbac-submit-api.yaml
  - rbac-dispatcher.yaml
  - networkpolicy-allow-submit-api.yaml
  - postgres/statefulset.yaml
  - submit-api/deployment.yaml
  - dispatcher/deployment.yaml
  - watcher/deployment.yaml

images:
  - name: cjob-submit-api
    newName: yusekiya/cjob-submit-api
    newTag: "1.2.0"
  - name: cjob-dispatcher
    newName: yusekiya/cjob-dispatcher
    newTag: "1.2.0"
  - name: cjob-watcher
    newName: yusekiya/cjob-watcher
    newTag: "1.2.0"

# StorageClass の指定
# 環境に応じて storageClassName を変更する場合はここを編集する
patches:
  - patch: |
      - op: replace
        path: /spec/storageClassName
        value: managed-nfs-storage
    target:
      kind: PersistentVolumeClaim
      name: cli-binary
  - patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: managed-nfs-storage
    target:
      kind: StatefulSet
      name: postgres
