apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-binary
  namespace: cjob-system
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: STORAGE_CLASS
  resources:
    requests:
      storage: 1Gi
